$axure.loadCurrentPage({
  "url":"home.html",
  "generationDate":new Date(1512554788610.01),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"51a37930ca0c498a8f35c9eb3d46f805",
    "type":"Axure:Page",
    "name":"Home",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"66f694cc2da24cb3901cc8e5959eaaad",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":-1,
              "y":0}},
          "adaptiveStyles":{
},
          "masterId":"6e6717e8b2bc47ba86e4fdb827d1fe77"}]}},
  "masters":{
    "6e6717e8b2bc47ba86e4fdb827d1fe77":{
      "packageId":"6e6717e8b2bc47ba86e4fdb827d1fe77",
      "type":"Axure:Master",
      "name":"新母版",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"a3700bcc94134dde86c6362fee8d60f4",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF4A66A5},
              "location":{
                "x":0,
                "y":80},
              "size":{
                "width":1599,
                "height":820},
              "borderFill":{
                "fillType":"solid",
                "color":0x797979}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2caf170ca4f2426d909ddf59448f3765",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF4A66A5},
                  "location":{
                    "x":0,
                    "y":80},
                  "size":{
                    "width":1599,
                    "height":820},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0x797979}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u1.png"}},
{
            "id":"b27815a9c9b6425da3a9821ee6c45431",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF900F09},
              "location":{
                "x":9,
                "y":99},
              "size":{
                "width":206,
                "height":35},
              "borderFill":{
                "fillType":"solid",
                "color":0x797979},
              "cornerRadiusTopLeft":"13"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"5c1cb275eaa04438894654b928611f6e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF900F09},
                  "location":{
                    "x":9,
                    "y":99},
                  "size":{
                    "width":206,
                    "height":35},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0x797979},
                  "cornerRadiusTopLeft":"13"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u3.png"}},
{
            "id":"1368540914654f228dfcf9a2145b449a",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF900F09},
              "location":{
                "x":9,
                "y":119},
              "size":{
                "width":206,
                "height":17},
              "borderFill":{
                "fillType":"solid",
                "color":0x797979}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"1775700c3f424da397472caef2a0fc02",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF900F09},
                  "location":{
                    "x":9,
                    "y":119},
                  "size":{
                    "width":206,
                    "height":17},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0x797979}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u5.png"}},
{
            "id":"33ba5e207d68414289a43fad59b12cb3",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"16px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":75,
                "y":110},
              "size":{
                "width":65,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"1a39e8633cd145f48c354e3a7591d891",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"16px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":75,
                    "y":110},
                  "size":{
                    "width":65,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"448a92e10d8d4f08bddb63d9700cb0dd",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'宋体 Regular', '宋体'",
              "fontSize":"12px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF5E5E5E,
                "opacity":1},
              "location":{
                "x":64,
                "y":747},
              "size":{
                "width":73,
                "height":14}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"edec651b69314319891ebf3ae9b358f8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'宋体 Regular', '宋体'",
                  "fontSize":"12px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF5E5E5E,
                    "opacity":1},
                  "location":{
                    "x":64,
                    "y":747},
                  "size":{
                    "width":73,
                    "height":14}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"6277d17afff847fe804c8a873acefc60",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFE7E7E7},
              "location":{
                "x":9,
                "y":212},
              "size":{
                "width":206,
                "height":677},
              "borderFill":{
                "fillType":"solid",
                "color":0x797979},
              "cornerRadiusTopLeft":"13"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2de73ada570546079fc603b29fe0592e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFE7E7E7},
                  "location":{
                    "x":9,
                    "y":212},
                  "size":{
                    "width":206,
                    "height":677},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0x797979},
                  "cornerRadiusTopLeft":"13"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u11.png"}},
{
            "id":"b636a8c9d86648be9f3d13f78539658d",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF29A1B1},
              "location":{
                "x":9,
                "y":82},
              "size":{
                "width":206,
                "height":130},
              "borderFill":{
                "fillType":"solid",
                "color":0x797979},
              "cornerRadiusTopLeft":"13"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c7187acd75814323a1da194e2270b158",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF29A1B1},
                  "location":{
                    "x":9,
                    "y":82},
                  "size":{
                    "width":206,
                    "height":130},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0x797979},
                  "cornerRadiusTopLeft":"13"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u13.png"}},
{
            "id":"121ef9f5e0af4de794a4b13f7a81d417",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Negreta', 'Arial'",
              "fontSize":"16px",
              "fontWeight":"700",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":87,
                "y":97},
              "size":{
                "width":49,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"424456c30c684dcfa58130b513432b12",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Negreta', 'Arial'",
                  "fontSize":"16px",
                  "fontWeight":"700",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":87,
                    "y":97},
                  "size":{
                    "width":49,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"48e86564c11243ccad44829649709011",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":230,
                "y":82},
              "size":{
                "width":1367,
                "height":807},
              "cornerRadiusTopLeft":"2"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b286d31648314d87b35e5896aa5274d2",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":230,
                    "y":82},
                  "size":{
                    "width":1367,
                    "height":807},
                  "cornerRadiusTopLeft":"2"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u17.png"}},
{
            "id":"e7c41d1231db4f4a8fcab486f38d4bf5",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":1323,
                "y":32},
              "size":{
                "width":96,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"820c40a7a1f64a5e85b1252f5e95d810",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":1323,
                    "y":32},
                  "size":{
                    "width":96,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"42f1a8d5a2a945198da3c141247dfd38",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF008000,
                "opacity":1},
              "location":{
                "x":18,
                "y":136},
              "size":{
                "width":19,
                "height":20},
              "rotation":"0",
              "textRotation":"0",
              "borderWidth":"0",
              "cornerRadiusTopLeft":"0"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"dcdff51cd0ef488e88c347393f4b9142",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF008000,
                    "opacity":1},
                  "location":{
                    "x":18,
                    "y":136},
                  "size":{
                    "width":19,
                    "height":20},
                  "rotation":"0",
                  "textRotation":"0",
                  "borderWidth":"0",
                  "cornerRadiusTopLeft":"0"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u21.png"}},
{
            "id":"7b336842befa4fe6ae1a28793b78ce03",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Negreta', 'Arial'",
              "fontSize":"36px",
              "fontWeight":"700",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":52,
                "y":125},
              "size":{
                "width":114,
                "height":42}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7f0053331336472387bb5dc5acc7dd9b",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Negreta', 'Arial'",
                  "fontSize":"36px",
                  "fontWeight":"700",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":52,
                    "y":125},
                  "size":{
                    "width":114,
                    "height":42}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"0529be263e724f3bbdc20f4c02da7508",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Negreta', 'Arial'",
              "fontSize":"16px",
              "fontWeight":"700",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":69,
                "y":179},
              "size":{
                "width":74,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b5ac567cf5ce416ebfb6b122e42e6936",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Negreta', 'Arial'",
                  "fontSize":"16px",
                  "fontWeight":"700",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":69,
                    "y":179},
                  "size":{
                    "width":74,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"0fa3dc58eb7748b2bfe26d7ddcf60940",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF4A66A5},
              "location":{
                "x":1,
                "y":0},
              "size":{
                "width":1597,
                "height":82},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"28a0db28146c41be9db8cce4e830997a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF4A66A5},
                  "location":{
                    "x":1,
                    "y":0},
                  "size":{
                    "width":1597,
                    "height":82},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u27.png"}},
{
            "id":"9094b574f6fc4fe8a5c08fb2f612efdb",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'楷体 Regular', '楷体'",
              "fontSize":"36px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFF00,
                "opacity":1},
              "location":{
                "x":251,
                "y":19},
              "size":{
                "width":289,
                "height":41}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7a7cc20146934c019539a3b73bfc3410",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'楷体 Regular', '楷体'",
                  "fontSize":"36px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF00,
                    "opacity":1},
                  "location":{
                    "x":251,
                    "y":19},
                  "size":{
                    "width":289,
                    "height":41}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"e5c6fdd8c0404f9dbd87fba59455547e",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Constantia Regular', 'Constantia'",
              "fontSize":"36px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":34,
                "y":19},
              "size":{
                "width":187,
                "height":44}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"00db3457645a41bd96d72cae3d246981",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Constantia Regular', 'Constantia'",
                  "fontSize":"36px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":34,
                    "y":19},
                  "size":{
                    "width":187,
                    "height":44}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"802f562de6fb4435acf7d5aae57deb56",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "location":{
                "x":234,
                "y":139},
              "size":{
                "width":1364,
                "height":10},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/home/u33_line.png"}},
{
            "id":"8c203a59984843799bebab418e4ea9d5",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":1213,
                "y":6},
              "size":{
                "width":358,
                "height":67}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c951b42e909d415f8bcac5b6f1b9eec8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":1213,
                    "y":6},
                  "size":{
                    "width":358,
                    "height":67}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u34.png"}},
{
            "id":"77e78092e89e484f9bf4b3d5c525dd71",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF4A66A5},
              "location":{
                "x":1391,
                "y":48},
              "size":{
                "width":200,
                "height":31},
              "borderFill":{
                "fillType":"solid",
                "color":0x797979}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"80d21979901e48c1b92d48911dfed430",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF4A66A5},
                  "location":{
                    "x":1391,
                    "y":48},
                  "size":{
                    "width":200,
                    "height":31},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0x797979}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u36.png"}},
{
            "id":"125f178c8897444ea842c6f012a087df",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Negreta', 'Arial'",
              "fontWeight":"700",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":1427,
                "y":56},
              "size":{
                "width":53,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"a6cc933b49a749eab8c850b81b950d93",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Negreta', 'Arial'",
                  "fontWeight":"700",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":1427,
                    "y":56},
                  "size":{
                    "width":53,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"c4b66b58cfe54c58b77b2cb5acaecfd4",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Negreta', 'Arial'",
              "fontWeight":"700",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":1508,
                "y":56},
              "size":{
                "width":53,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"4043cdfb99bc4069a29d987dfd509a0e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Negreta', 'Arial'",
                  "fontWeight":"700",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":1508,
                    "y":56},
                  "size":{
                    "width":53,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"8cb59351523a4607b3e8fa93eb863173",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Arial Negreta', 'Arial'",
              "fontSize":"16px",
              "fontWeight":"700",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFF4A66A5},
              "location":{
                "x":1251,
                "y":26},
              "size":{
                "width":130,
                "height":31},
              "borderFill":{
                "fillType":"solid",
                "color":0x797979}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e388ec30d4c54b94886a1af21d7df37d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Negreta', 'Arial'",
                  "fontSize":"16px",
                  "fontWeight":"700",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF4A66A5},
                  "location":{
                    "x":1251,
                    "y":26},
                  "size":{
                    "width":130,
                    "height":31},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0x797979}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u42.png"}},
{
            "id":"5283e9abfca44e01943c976684020d7d",
            "label":"",
            "type":"referenceDiagramObject",
            "styleType":"referenceDiagramObject",
            "visible":true,
            "style":{
},
            "adaptiveStyles":{
},
            "masterId":"e6b9dac5456c4496b3f89523df8e9025"},
{
            "id":"fb503d141c97473aba0b592710f34456",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":249,
                "y":108},
              "size":{
                "width":66,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"fa6b4d0a1bcb45d7b5b10761f7f2aa89",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":249,
                    "y":108},
                  "size":{
                    "width":66,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"76eacb7b68cb476aba6a9acc201b32a2",
            "label":"",
            "type":"verticalLine",
            "styleType":"verticalLine",
            "visible":true,
            "style":{
              "location":{
                "x":234,
                "y":109},
              "size":{
                "width":10,
                "height":14},
              "borderWidth":"3",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF0000FF}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/home/u53_line.png"}},
{
            "id":"2115be84f23b48fb9ed8a2576f974229",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":316,
                "y":108},
              "size":{
                "width":27,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"0f13022cf6f74630a81a6c3be55ce647",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":316,
                    "y":108},
                  "size":{
                    "width":27,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}},
    "e6b9dac5456c4496b3f89523df8e9025":{
      "packageId":"e6b9dac5456c4496b3f89523df8e9025",
      "type":"Axure:Master",
      "name":"导航",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"2f293c0d4c3c439283eca48544a75d59",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFF4A66A5},
              "location":{
                "x":9,
                "y":265},
              "size":{
                "width":206,
                "height":37},
              "cornerRadiusTopLeft":"5"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f4b21108f0184df193f7d47621b396f9",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF4A66A5},
                  "location":{
                    "x":9,
                    "y":265},
                  "size":{
                    "width":206,
                    "height":37},
                  "cornerRadiusTopLeft":"5"},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 用户管理",
                        "target":{
                          "targetType":"page",
                          "url":"用户管理.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/home/u45.png"}},
{
            "id":"2b34a5cf5ed044f1890c9253b2989b54",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFF4A66A5},
              "location":{
                "x":9,
                "y":222},
              "size":{
                "width":206,
                "height":37},
              "cornerRadiusTopLeft":"5"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"9684166d76c040b3b50a190abe06898c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF4A66A5},
                  "location":{
                    "x":9,
                    "y":222},
                  "size":{
                    "width":206,
                    "height":37},
                  "cornerRadiusTopLeft":"5"},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 薪资查询",
                        "target":{
                          "targetType":"page",
                          "url":"薪资查询.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/home/u45.png"}},
{
            "id":"2fe0d32aa3d147928d8624da42422dd5",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFF4A66A5},
              "location":{
                "x":9,
                "y":309},
              "size":{
                "width":206,
                "height":37},
              "cornerRadiusTopLeft":"5"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"fe4f64931f0f42ff9924d9a7721fb6df",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF4A66A5},
                  "location":{
                    "x":9,
                    "y":309},
                  "size":{
                    "width":206,
                    "height":37},
                  "cornerRadiusTopLeft":"5"},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 记录管理",
                        "target":{
                          "targetType":"page",
                          "url":"记录管理.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/home/u45.png"}}]}}},
  "objectPaths":{
    "66f694cc2da24cb3901cc8e5959eaaad":{
      "scriptId":"u0",
      "a3700bcc94134dde86c6362fee8d60f4":{
        "scriptId":"u1"},
      "2caf170ca4f2426d909ddf59448f3765":{
        "scriptId":"u2"},
      "b27815a9c9b6425da3a9821ee6c45431":{
        "scriptId":"u3"},
      "5c1cb275eaa04438894654b928611f6e":{
        "scriptId":"u4"},
      "1368540914654f228dfcf9a2145b449a":{
        "scriptId":"u5"},
      "1775700c3f424da397472caef2a0fc02":{
        "scriptId":"u6"},
      "33ba5e207d68414289a43fad59b12cb3":{
        "scriptId":"u7"},
      "1a39e8633cd145f48c354e3a7591d891":{
        "scriptId":"u8"},
      "448a92e10d8d4f08bddb63d9700cb0dd":{
        "scriptId":"u9"},
      "edec651b69314319891ebf3ae9b358f8":{
        "scriptId":"u10"},
      "6277d17afff847fe804c8a873acefc60":{
        "scriptId":"u11"},
      "2de73ada570546079fc603b29fe0592e":{
        "scriptId":"u12"},
      "b636a8c9d86648be9f3d13f78539658d":{
        "scriptId":"u13"},
      "c7187acd75814323a1da194e2270b158":{
        "scriptId":"u14"},
      "121ef9f5e0af4de794a4b13f7a81d417":{
        "scriptId":"u15"},
      "424456c30c684dcfa58130b513432b12":{
        "scriptId":"u16"},
      "48e86564c11243ccad44829649709011":{
        "scriptId":"u17"},
      "b286d31648314d87b35e5896aa5274d2":{
        "scriptId":"u18"},
      "e7c41d1231db4f4a8fcab486f38d4bf5":{
        "scriptId":"u19"},
      "820c40a7a1f64a5e85b1252f5e95d810":{
        "scriptId":"u20"},
      "42f1a8d5a2a945198da3c141247dfd38":{
        "scriptId":"u21"},
      "dcdff51cd0ef488e88c347393f4b9142":{
        "scriptId":"u22"},
      "7b336842befa4fe6ae1a28793b78ce03":{
        "scriptId":"u23"},
      "7f0053331336472387bb5dc5acc7dd9b":{
        "scriptId":"u24"},
      "0529be263e724f3bbdc20f4c02da7508":{
        "scriptId":"u25"},
      "b5ac567cf5ce416ebfb6b122e42e6936":{
        "scriptId":"u26"},
      "0fa3dc58eb7748b2bfe26d7ddcf60940":{
        "scriptId":"u27"},
      "28a0db28146c41be9db8cce4e830997a":{
        "scriptId":"u28"},
      "9094b574f6fc4fe8a5c08fb2f612efdb":{
        "scriptId":"u29"},
      "7a7cc20146934c019539a3b73bfc3410":{
        "scriptId":"u30"},
      "e5c6fdd8c0404f9dbd87fba59455547e":{
        "scriptId":"u31"},
      "00db3457645a41bd96d72cae3d246981":{
        "scriptId":"u32"},
      "802f562de6fb4435acf7d5aae57deb56":{
        "scriptId":"u33"},
      "8c203a59984843799bebab418e4ea9d5":{
        "scriptId":"u34"},
      "c951b42e909d415f8bcac5b6f1b9eec8":{
        "scriptId":"u35"},
      "77e78092e89e484f9bf4b3d5c525dd71":{
        "scriptId":"u36"},
      "80d21979901e48c1b92d48911dfed430":{
        "scriptId":"u37"},
      "125f178c8897444ea842c6f012a087df":{
        "scriptId":"u38"},
      "a6cc933b49a749eab8c850b81b950d93":{
        "scriptId":"u39"},
      "c4b66b58cfe54c58b77b2cb5acaecfd4":{
        "scriptId":"u40"},
      "4043cdfb99bc4069a29d987dfd509a0e":{
        "scriptId":"u41"},
      "8cb59351523a4607b3e8fa93eb863173":{
        "scriptId":"u42"},
      "e388ec30d4c54b94886a1af21d7df37d":{
        "scriptId":"u43"},
      "5283e9abfca44e01943c976684020d7d":{
        "scriptId":"u44",
        "2f293c0d4c3c439283eca48544a75d59":{
          "scriptId":"u45"},
        "f4b21108f0184df193f7d47621b396f9":{
          "scriptId":"u46"},
        "2b34a5cf5ed044f1890c9253b2989b54":{
          "scriptId":"u47"},
        "9684166d76c040b3b50a190abe06898c":{
          "scriptId":"u48"},
        "2fe0d32aa3d147928d8624da42422dd5":{
          "scriptId":"u49"},
        "fe4f64931f0f42ff9924d9a7721fb6df":{
          "scriptId":"u50"}},
      "fb503d141c97473aba0b592710f34456":{
        "scriptId":"u51"},
      "fa6b4d0a1bcb45d7b5b10761f7f2aa89":{
        "scriptId":"u52"},
      "76eacb7b68cb476aba6a9acc201b32a2":{
        "scriptId":"u53"},
      "2115be84f23b48fb9ed8a2576f974229":{
        "scriptId":"u54"},
      "0f13022cf6f74630a81a6c3be55ce647":{
        "scriptId":"u55"}}}});